version: '3.7'
services:
  stayfit.api:
    image: ${DOCKER_REGISTRY-}stayfitapi
    build:
      context: .
      dockerfile: Presentation/StayFit.API/Dockerfile
    depends_on:
      - redis
      - postgres
    networks:
      - stayfit_network


  redis:
    container_name: redis
    image: redis/redis-stack:latest
    networks:
      - stayfit_network
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: StayFitDb
    networks:
      - stayfit_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - stayfit_network
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: always

networks:
  stayfit_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  seq_data: